### ISSUE TITLE
Week number (W) calculated wrong when you try 12/29/2014 ( giving 1 )

### ISSUE THREAD

**Issue by andreytech** [jacwright/date.format#13]
Hello!
I am doing this:
var date_obj = new Date('2014-12-29');
var week_number = date_obj.format('W'); // returns 1
Same thing for 30 and 31 ( probably related to a fact that 29th is Monday)

Thanks,
Andrey

**Comment by althoul** [comment]
Hello,

Your problem is "29/12/2014 to 04/01/2015 is week 1 of year 2015", right ?
In this cas, this is correct. When the last week of the year has strictly less than 4 days, this is the week 1 of the next year and not the week 53 of the current year, that's normal.

**Comment by andreytech** [comment]
Hello Sylvain,

It is actually giving me week 1 of 2014

**Comment by althoul** [comment]
Ah yes, the problem is the distinction between year and week. It would be needed a one more letter for "year for week"...

**Comment by andreytech** [comment]
Yes, it will definitely help!

**Comment by kevit-development** [comment]
As Sylain (Deleted user) said, it's because 29th December 2014 falls in the 1st week of 2015. This is because there are 3 days (29-30-31) for 2014 and (1-2-3-4) for 2015, because 2014 has less days in the week than 2015, it's becomming the first week of 2015 (eventho it's clearly 2014). Calendars work weird, hehe.
